MyShop.web/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using MyShop_DataAccess.Data;
using MyShop_Entities.Helper;
using MyShop_Entities.Models;
using MyShop_Entities.Repositories;

namespace MyShop.web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public CategoryController(IUnitOfWork unitOfWork , IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            var category = _unitOfWork.Categories.GetAll();
            return View(category);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category , IFormFile file)
        {
            
            if (ModelState.IsValid)
            {
                string rootPath = _webHostEnvironment.WebRootPath; // mean wwwroot
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var upload = Path.Combine(rootPath, @"Images\Category");
                    var extension = Path.GetExtension(file.FileName);

                    using (var filestream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(filestream);

                    }
                    category.Image= @"Images\Category\" + fileName + extension;
                }

                _unitOfWork.Categories.Add(category);
                _unitOfWork.Complet();
                TempData["Create"] = "تم انشاء فئه جديده بنجاح";
                return RedirectToAction("Index");
            }
            return View(category);

        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var category = _unitOfWork.Categories.GetFirstOrDefualt(x => x.Id == id);
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                var categoryFromDb = _unitOfWork.Categories.GetFirstOrDefualt(x => x.Id == category.Id);
                if (categoryFromDb == null)
                {
                    return NotFound();
                }

                string rootPath = _webHostEnvironment.WebRootPath; // mean wwwroot
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var upload = Path.Combine(rootPath, @"Images\Category");
                    var extension = Path.GetExtension(file.FileName);

                    if (category.Image != null)
                    {
                        var oldImage = Path.Combine(rootPath, category.Image.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImage))
                        {
                            System.IO.File.Delete(oldImage);
                        }

                    }

                    using (var filestream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(filestream);

                    }
                    category.Image = @"Images\Category\" + fileName + extension;
                }

                categoryFromDb.Name = category.Name;
                categoryFromDb.Description = category.Description;

                _unitOfWork.Categories.Update(categoryFromDb);
                _unitOfWork.Complet();
                TempData["Edit"] = "تم تعديل الفئه بنجاح";
                return RedirectToAction("Index");
            }

            return View(category);
        }



        [HttpGet]
        public IActionResult Delete(int? id)
        {
            var category = _unitOfWork.Categories.GetFirstOrDefualt(x => x.Id == id);
            return View(category);
        }

        [HttpPost]
        public IActionResult DeleteCategory(int? id)
        {
            var category = _unitOfWork.Categories.GetFirstOrDefualt(x => x.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            if (category.Image != null && category.Image != Guid.Empty.ToString())
            {
                var pathimage = Path.Combine(@"wwwroot/", Helpers.imagesSaveCategory, category.Image);
                if (System.IO.File.Exists(pathimage))
                {
                    System.IO.File.Delete(pathimage);
                }
            }
            _unitOfWork.Categories.Delete(category);
            _unitOfWork.Complet();
            TempData["Delete"] = "تم حذف الفئه بنجاح";
            return RedirectToAction("Index");
        }

        private void Image(Category model)
        {
            var file = HttpContext.Request.Form.Files;
            //Create
            if (file.Count() > 0)
            {
                var ImageName = Guid.NewGuid().ToString() + Path.GetExtension(file[0].FileName);
                var fileStream = new FileStream(Path.Combine(@"wwwroot/", Helpers.imagesSaveCategory, ImageName), FileMode.Create);
                file[0].CopyTo(fileStream);
                model.Image = ImageName;
            }
           
            else // Update
            {
                model.Image = model.Image;
            }
        }
    }
}

MyShop.web/Areas/Customer/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyShop_Entities.Helper;
using MyShop_Entities.Models;
using MyShop_Entities.Repositories;
using MyShop_Entities.ViewModels;
using Stripe.BillingPortal;
using Stripe.Checkout;
using System.Security.Claims;
using Session = Stripe.Checkout.Session;
using SessionCreateOptions = Stripe.Checkout.SessionCreateOptions;
using SessionService = Stripe.Checkout.SessionService;

namespace MyShop.web.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            // get user id is active now from database using claims
            var claimasIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimasIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var cart = new ShoppingCartViewModel()
            {
                CardList = _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == claim.Value , includeWord: "Product" ),
                Category = _unitOfWork.Categories.GetAll(),
                Order = new Order()
            }; 
            
            // to calculate the total price
            foreach (var item in cart.CardList)
            {
                cart.TotalPrice += (item.Count * item.Product.Price);
            }

            return View(cart);
        }
        [HttpPost]
        public IActionResult plus(int cartid)
        {
            //var cart = _unitOfWork.ShoppingCart.GetFirstOrDefualt(x => x.Id == cartid);

            //if(cart!= null)
            //{
            //    _unitOfWork.ShoppingCart.InceaseCount(cart, 1);
            //    _unitOfWork.Complet();

            //    var count = _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == cart.ApplicationUserId).Sum(x=>x.Count);
            //    HttpContext.Session.SetInt32(Helpers.SessionKey, count);
            //}

            //return RedirectToAction("Index");

            // use ajax 

            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefualt(x => x.Id == cartid);

            if (cart != null)
            {
                //  _unitOfWork.ShoppingCart.InceaseCount(cart , 1);
                var count = cart.Count += 1;
                _unitOfWork.Complet();

             //   var totalPrice = GetTotalPrice(); // Adjust the logic for calculating the total price

             //   var count = _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == cart.ApplicationUserId).Sum(x => x.Count);
                HttpContext.Session.SetInt32(Helpers.SessionKey, count);

                return Json(new { success = true, message = "Product added", totalPrice = GetTotalPrice(cart.ApplicationUserId), itemCount = count });
            }

            return Json(new { success = false, message = "Error occurred" });


        }
        [HttpPost]
        public IActionResult minuis(int cartid)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefualt(x => x.Id == cartid);

            if (cart == null)
            {
                return Json(new { success = false, message = "Cart item not found" });
            }

            bool itemRemoved = false;
            int itemCount = cart.Count;

            if (cart.Count <= 1)
            {
                // Remove item if count is less than or equal to 1
                _unitOfWork.ShoppingCart.Delete(cart);
                itemRemoved = true;
            }
            else
            {
                // Decrease count by 1 if count is greater than 1
                cart.Count -= 1;
                itemCount = cart.Count; // Update the item count after decrementing
               // _unitOfWork.ShoppingCart.Add(cart); // Ensure the updated cart is saved
            }

            _unitOfWork.Complet(); // Commit the changes

            // Calculate the total price after modification
            var totalPrice = GetTotalPrice(cart.ApplicationUserId);

            return Json(new
            {
                success = true,
                message = itemRemoved ? "Item removed" : "Product updated",
                totalPrice = totalPrice,
                itemCount = itemCount, // Return the updated item count
                itemRemoved = itemRemoved // Inform the front-end if the item was removed
            });
        }





        public IActionResult Remove(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefualt(x => x.Id == cartId);

            if (cart != null)
            {
                _unitOfWork.ShoppingCart.Delete(cart);
                _unitOfWork.Complet();

                var count = _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == cart.ApplicationUserId).Sum(x => x.Count);
                HttpContext.Session.SetInt32(Helpers.SessionKey, count);

                return Json(new
                {
                    success = true,
                    message = "Product removed",
                    totalPrice = GetTotalPrice(cart.ApplicationUserId),
                    itemCount = count,
                    itemRemoved = true // Send flag to inform if the item was removed
                });
            }

            return Json(new { success = false, message = "Error occurred" });
        }


        private decimal GetTotalPrice(string userId)
        {
            var cartItems = _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == userId, includeWord: "Product");
            return cartItems.Sum(x => x.Count * x.Product.Price);
        }


        [HttpGet]
        public IActionResult Summary()
        {
            // get user id is active now from database using claims
            var claimasIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimasIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var cart = new ShoppingCartViewModel()
            {
                CardList = _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == claim.Value, includeWord: "Product"),
                Category = _unitOfWork.Categories.GetAll(),
                Order = new Order(),
          
            };

            cart.Order.ApplicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefualt(x => x.Id == claim.Value);
            // Fill data in order at summary card 
            cart.Order.Name = cart.Order.ApplicationUser.Name;
            cart.Order.Email = cart.Order.ApplicationUser.Email;
            cart.Order.Address = cart.Order.ApplicationUser.Address;
            cart.Order.PhoneNumber = cart.Order.ApplicationUser.PhoneNumber; 
            cart.Order.City = cart.Order.ApplicationUser.City;  

            // to calculate the total price
            foreach (var item in cart.CardList)
            {
                cart.TotalPrice += (item.Count * item.Product.Price);
            }
            return View(cart);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
		public IActionResult Summary(ShoppingCartViewModel cart)
		{
            // get user id is active now from database using claims
            // Get the current user's ID from claims
            var claimasIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimasIdentity.FindFirst(ClaimTypes.NameIdentifier);

            cart.CardList = _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == claim.Value  , includeWord: "Product");

            // Fill data at Strip 
            // Fetch the user's shopping cart items
            if (cart.Order == null )
            {
                cart.Order = new Order();

            }
            // Set order details (mark as approved)

            cart.Order.OrderStatus = Helpers.Approve;
            cart.Order.PaymentStatus = Helpers.Approve;
            cart.Order.OrderDate = DateTime.Now;
            cart.Order.UserId = claim.Value;



            // to calculate the total price
            // Calculate the total price of the order

            foreach (var item in cart.CardList)
			{
				cart.TotalPrice += (item.Count * item.Product.Price);
			}
            cart.Order.TotalPrice = cart.TotalPrice;
            _unitOfWork.Order.Add(cart.Order);
            _unitOfWork.Complet();

            // Strip part "Payment"
            // Save each cart item as an order detail

            foreach (var item in cart.CardList)
            {
                var orderDetail = new OrderDetail()
                {
                    ProductId = item.ProductId,
                    OrderId = cart.Order.Id,
                    Price = item.Product.Price,
                    Count = item.Count,
                };
                _unitOfWork.OrderDetails.Add(orderDetail);
                _unitOfWork.Complet();
            }

            // will remove this part when larama need to turn on stripe
            // Clear the shopping cart for the user after the order is confirmed
            foreach (var item in cart.CardList)
            {
                _unitOfWork.ShoppingCart.Delete(item);
            }

            _unitOfWork.Complet();  // Commit the changes


            // part of stripe
            //var domain = "https://localhost:44317/";
            //var options = new SessionCreateOptions
            //{
            //    LineItems = new List<SessionLineItemOptions>(),
            //    Mode="payment",
            //    SuccessUrl = domain+$"customer/cart/orderconfirmation?id={cart.Order.Id}",
            //    CancelUrl= domain+$"customer/cart/index",

            //};

            //foreach (var item in cart.CardList)
            //{
            //    var sessionOptins = new SessionLineItemOptions
            //    {
            //        PriceData = new SessionLineItemPriceDataOptions
            //        {

MyShop.web/ViewComponunts/ShoppingCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyShop_Entities.Repositories;
using System.Security.Claims;
using MyShop_Entities.Helper;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MyShop.web.ViewComponunts
{
    // ViewComponent => like a partialView but this using when i want a big bessnis logic 
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimasIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimasIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim != null)
            {
                if(HttpContext.Session.GetInt32(Helpers.SessionKey) != null)
                {
                    return View(HttpContext.Session.GetInt32(Helpers.SessionKey));
                }
                else
                {
                    HttpContext.Session.SetInt32(Helpers.SessionKey, _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == claim.Value).ToList().Count());
                    return View(HttpContext.Session.GetInt32(Helpers.SessionKey));
                    
                }

            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

MyShop.web/Views/Shared/_Customer.cshtml
@using Microsoft.AspNetCore.Http
@using MyShop_Entities.Helper;
@inject IHttpContextAccessor httpContextAccesor

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Shop Homepage</title>
    <link rel="icon" type="image/png" href="~/notebookIcon.png" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="~/Customer/css/styles.css" rel="stylesheet" />

    <style>
        /* Navbar */
        .navbar {
            background-color: #f4efe9; /* White background for navbar */
            border-bottom: 2px solid #e0e0e0; /* Light border for separation */
        }

            .navbar .nav-link,
            .navbar-brand {
                color: #333333; /* Darker text color for contrast */
            }

                .navbar .nav-link:hover,
                .navbar-brand:hover {
                    color: #333333; /* Darker color on hover */
                }

        .navbar-toggler-icon {
            background-color: #f4efe9; /* Dark icon color */
        }

        /* Footer */
        footer {
            background-color: #f4efe9; /* White background for footer */
            color: #333333; /* Darker text color */
            border-top: 2px solid #e0e0e0; /* Light border for separation */
        }

            footer a {
                color: #555555; /* Darker color for footer links */
            }

                footer a:hover {
                    color: #000000; /* Darker color on hover */
                }

        /* Brown tones for the rest of the page */
        body {
            background-color: #f5f5f5; /* Light brown background */
            color: #4e342e; /* Dark brown text color */
        }

        .btn-outline-dark {
            border-color: #8B4513; /* Brown border for buttons */
            color: #8B4513; /* Brown text color for buttons */
        }

            .btn-outline-dark:hover {
                background-color: #8B4513; /* Brown background on hover */
                color: #ffffff; /* White text on hover */
            }

        .badge.bg-dark {
            background-color: #4e342e; /* Dark brown background for badges */
        }

        .dropdown-menu {
            background-color: #8B4513; /* Brown background for dropdown */
        }

        .dropdown-item {
            color: #ffffff; /* White text for dropdown items */
        }

            .dropdown-item:hover {
                background-color: #6f3e1b; /* Darker brown on hover */
            }
    </style>
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">
                <img src="~/fekra-logo.png" style="height:40px;"/>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"></a>
                    </li>
                    @if (User.IsInRole(Helpers.AdminRole))
                    {
                        <li class="nav-item"><a class="nav-link" href="/Admin/Dashboard/index">لوحه التحكم</a></li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                       @*  <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart"
                               asp-action="Index">سله الطلبات</a>
                        </li> *@
                    }
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">التفاصيل</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <hr class="dropdown-divider" />
                            </li>
                            @if (User.IsInRole(Helpers.AdminRole))
                            {
                                <li class="dropdown-item">
                                    <a class="nav-link" href="/Admin/Dashboard/index">
                                        لوحه 
                                        التحكم
                                    </a>
                                </li>
                            }
                            @if (User.Identity.IsAuthenticated)
                            {
                               @*  <li class="dropdown-item">
                                    <a class="nav-link" asp-area="Customer"
                                       asp-controller="Cart" asp-action="Index">سله الطلبات</a>
                                </li> *@
                            }
                        </ul>
                    </li>
                </ul>
                <!-- Search Form -->
                <form class="d-flex ms-auto" asp-area="Customer" asp-controller="Home" asp-action="Search" method="get">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"
                           name="query">
                    <button class="btn btn-outline-dark" type="submit">بحث</button>
                </form>
                <!-- Search Form -->
                <partial name="_LoginPartial" />
                @if (User.Identity.IsAuthenticated)
                {
                    <form class="d-flex">
                        <a href="/Customer/Cart/Index" class="btn btn-outline-dark">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            @*   @await Component.InvokeAsync("ShoppingCart") *@
                            @*   لو ف داتا جوه السيشن دا  اعرضها *@
                            @if (httpContextAccesor.HttpContext.Session.GetInt32(Helpers.SessionKey) != null)
                            {
                                <span class="badge bg-dark text-white ms-1 rounded-pill">
                                    @httpContextAccesor.HttpContext.Session.GetInt32(Helpers.SessionKey)
                                </span>
                            }
                            else
                            {
                                <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                            }
                        </a>
                    </form>
                }
            </div>
        </div>
    </nav>

    <!-- Header-->
    <!-- Section-->
    @RenderBody()

    <!-- Footer-->
    <footer class="py-5">
        <div class="container">
            <p class="m-0 text-center text-dark">Copyright &copy; Abdalla Frieg tel:01559091117</p>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/Customer/js/scripts.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

MyShop.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyShop.web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyShop.web.styles.css" asp-append-version="true" />
@*     !-- or if using PNG --> *@
   <link rel="icon" type="image/png" href="~/notebookIcon.png" /> 

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>       
                </button> 
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Abddalla Frieg tel: 01559091117 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyShop.web/Views/Shared/_Toster.cshtml
@if (TempData["Create"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr["success"]("@TempData["Create"]")

    </script>
}

@if (TempData["Edit"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr["info"]("@TempData["Edit"]")

    </script>
}


@if (TempData["Delete"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr["error"]("@TempData["Delete"]")

    </script>
}